#dist: trusty

language: c

compiler:
  - cmake
  - make

branches:
  only:
  - master

install:
  - sudo apt install cmake gcc lcov cppcheck python-pip valgrind flawfinder doxygen dot
  - sudo pip install --user -r c-test/docs/requirements.txt
  
script:
  - mkdir build
  - cd build
  - cmake ../c-test -DBUILD_COVERAGE=1 -DBUILD_HTML_COVERAGE=1 -DUSE_VALGRIND=1 -DRUN_CPPCHECK=1
  - make
  - make test
  - make coverage
 
