name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_lib
      run: sudo apt-get install cmake gcc lcov cppcheck python3-pip valgrind flawfinder doxygen graphviz
    - name: update_pip
      run: pip install --user -r ../../docs/requirment.txt
    #- name: configure
    #  run: ./configure
    - name: ws
      run: ls -al ; pwd ;
    - name: clone
      run: git clonne https://github.com/nakyto/Project_C ; cd ./Project_C
      
    - name: compil
      run: mkdir build ; cd build  
    - name: cmake
      run: cmake ../c-test -DBUILD_COVERAGE=1 -DBUILD_HTML_COVERAGE=1 -DUSE_VALGRIND=1 -DRUN_CPPCHECK=1
    - name: make 
      run: make
    - name: make test
      run: make test
    - name: make covrage
      run: make coverage
      
